name: flutter_websocket
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  web_socket_channel: ^3.0.2
  fl_chart: ^0.63.0
  charts_flutter: ^0.12.0
  google_generative_ai: ^0.4.6
  firebase_core: ^3.12.0
  flutter_dotenv: ^5.2.1
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.5.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.3
  path: ^1.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env