// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFvyEaQPCQ2meFNQ2ybJYedeTxqiYzJiE',
    appId: '1:794891095241:web:4e8ae4c90af7803c265118',
    messagingSenderId: '794891095241',
    projectId: 'websocket-f966f',
    authDomain: 'websocket-f966f.firebaseapp.com',
    storageBucket: 'websocket-f966f.firebasestorage.app',
    measurementId: 'G-Y1HZYXFDF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoM3pImDz3av7aFInPWTZ1Mik9fGr8plQ',
    appId: '1:794891095241:android:c016bcf08e958c98265118',
    messagingSenderId: '794891095241',
    projectId: 'websocket-f966f',
    storageBucket: 'websocket-f966f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCci2HHEpIQ_d7srrnNqiCTvC14aa5ROB0',
    appId: '1:794891095241:ios:6a0f68bbdbd40366265118',
    messagingSenderId: '794891095241',
    projectId: 'websocket-f966f',
    storageBucket: 'websocket-f966f.firebasestorage.app',
    iosBundleId: 'com.example.flutterWebsocket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCci2HHEpIQ_d7srrnNqiCTvC14aa5ROB0',
    appId: '1:794891095241:ios:6a0f68bbdbd40366265118',
    messagingSenderId: '794891095241',
    projectId: 'websocket-f966f',
    storageBucket: 'websocket-f966f.firebasestorage.app',
    iosBundleId: 'com.example.flutterWebsocket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFvyEaQPCQ2meFNQ2ybJYedeTxqiYzJiE',
    appId: '1:794891095241:web:52f16671629a7ea0265118',
    messagingSenderId: '794891095241',
    projectId: 'websocket-f966f',
    authDomain: 'websocket-f966f.firebaseapp.com',
    storageBucket: 'websocket-f966f.firebasestorage.app',
    measurementId: 'G-3DGXSZFG0S',
  );
}
